dubbo:
  application:
    name: product_service
    registry:
      protocol: zookeeper
      address: 101.132.71.169:2181
  protocol:
    port: 20900

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v13?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: HF9DswlYD9c3P1ij5vZC14zKMcEfED137P/7QIUU5KIIVA78+hdFtb8KprCDj0qVbfHN/fpYy78bxIyZDiaYyw==
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}

public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKrrHlcvSmDTXkywJVuzjffrTFKy3eCFqhkPbqRIhyxMwDS0IaccGGghmKpcKEBKRpyJeyFjAv4B02+dGj8UINcCAwEAAQ==

pagehelper:
  helper-dialect: mysql
  reasonable: true


