dubbo:
  application:
    name: center_web
  registry:
    protocol: zookeeper
    address: 101.132.71.169:2181
server:
  port: 9090
spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 101.132.71.169
    port: 5672
    username: kdx
    password: 123123
    virtual-host: /kdx

pagehelper:
  helper-dialect: mysql
  reasonable: true
fdfs:
  so-timeout: 3000
  connect-timeout: 3000
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 101.132.71.169:22122
image:
  url: http://101.132.71.169/


