dubbo:
  application:
    name: search_web
  registry:
    protocol: zookeeper
    address: 101.132.71.169:2181
server:
  port: 9092
  servlet:
    context-path: /
spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 101.132.71.169
    port: 5672
    username: kdx
    password: 123123
    virtual-host: /kdx
