server:
  port: 9093
  servlet:
    context-path: /
dubbo:
  application:
    name: item_web
  registry:
    protocol: zookeeper
    address: 101.132.71.169:2181
spring:
  rabbitmq:
    host: 101.132.71.169
    port: 5672
    username: kdx
    password: 123123
    virtual-host: /kdx